### ISSUE TITLE
可以贴边自动修改方向吗

### ISSUE THREAD

**Issue by edifangyi** [xujiaji/HappyBubble#1]
除了定制化。要是默认配置，可以贴边自动修改显示方向吗

**Comment by xujiaji** [comment]
你说的贴边修改显示方向是什么意思呢？意思是上下左右随机，一边空间不够了显示在空间够的那边吗？

**Comment by edifangyi** [comment]
@xujiaji 是的呢

**Comment by edifangyi** [comment]
@第二种

**Comment by xujiaji** [comment]
@edifangyi 可以一试

**Comment by xujiaji** [comment]
@edifangyi 
目前实现的如下展示功能：
1、设置自动位置后，将Dialog展示到被点击控件距离边缘最大控件的方向。
2、勾选穿透事件后，事件交互会被传递到底部activity。
[测试apk.zip 下载](https://github.com/xujiaji/HappyBubble/files/1605732/Apk.zip)
![GIF展示](https://user-images.githubusercontent.com/16447251/34597778-dcfb265c-f223-11e7-9c95-27e0f67d148b.gif)

**Comment by edifangyi** [comment]
@xujiaji  谢谢 辛苦~

**Comment by xujiaji** [comment]
@edifangyi 恩恩，有时间可以的话看看上面的apk有什么问题或其他的建议吗？如果没有问题我在测测，周末才会更新版本了哦！

**Comment by xujiaji** [comment]
已更新版本1.1.0
