### ISSUE TITLE
横屏模式下位置有问题

### ISSUE THREAD

**Issue by itpers** [xujiaji/HappyBubble#10]
横屏模式下, 弹窗位置显示有问题
![image](https://user-images.githubusercontent.com/9130729/50323726-f555be00-0515-11e9-99f3-4ff63b74fa4f.png)

![image](https://user-images.githubusercontent.com/9130729/50323737-043c7080-0516-11e9-830c-19c584e08212.png)

![image](https://user-images.githubusercontent.com/9130729/50323741-0acae800-0516-11e9-86bd-65a97b0e889b.png)

**Comment by xujiaji** [comment]
看这偏离的距离有可能是因为底部虚拟按键的高度，下午我试试

**Comment by xujiaji** [comment]
@itpers 我更新了一下代码，你下载`happy-bubble`作为module导入项目试试呢

**Comment by xujiaji** [comment]
已更新，v1.1.7已修复
