### ISSUE TITLE
autoPosition未生效

### ISSUE THREAD

**Issue by protectedMan** [xujiaji/HappyBubble#13]
![image](https://user-images.githubusercontent.com/17565737/55678614-363fda00-592f-11e9-941f-08ed5e9ce71d.png)
代码是这样设置的

效果是这样的
 
![QQ20190407-121931-HD](https://user-images.githubusercontent.com/17565737/55678646-d433a480-592f-11e9-9ef8-cac3e6b289f5.gif)

**Comment by xujiaji** [comment]
你试试导入项目呢！我之前没更新远程仓库

**Comment by protectedMan** [comment]
导入libary可以了，不过遇到了新问题 
![image](https://user-images.githubusercontent.com/17565737/55679341-6fcb1200-593c-11e9-8c35-930d83e08171.png)，
气泡位置不对
![QQ20190407-135337-HD](https://user-images.githubusercontent.com/17565737/55679352-bb7dbb80-593c-11e9-8a0a-b7ae6fec5deb.gif)

**Comment by xujiaji** [comment]
calbar为true呢

**Comment by protectedMan** [comment]
> calbar为true呢

一样的效果

**Comment by xujiaji** [comment]
稍等，我试试

**Comment by xujiaji** [comment]
之前你直接设置显示在下方会不会偏移？

**Comment by xujiaji** [comment]
![image](https://user-images.githubusercontent.com/16447251/55679828-b45aab80-5944-11e9-8101-9b4633a4986e.png)
将画圈的true改为false

**Comment by protectedMan** [comment]
我刚试了一下，可以了，没问题了。
还望尽快更新maven版本

**Comment by xujiaji** [comment]
已更新
