### ISSUE TITLE
两处bug，看动态图

### ISSUE THREAD

**Issue by protectedMan** [xujiaji/HappyBubble#14]

**Comment by protectedMan** [comment]
![QQ20190411-093858-HD](https://user-images.githubusercontent.com/17565737/55924748-b28f3180-5c3d-11e9-832d-48f8b3a0ecf5.gif)

**Comment by protectedMan** [comment]
![QQ20190411-094027-HD](https://user-images.githubusercontent.com/17565737/55924812-e9654780-5c3d-11e9-8d18-5fe72bcd5775.gif)

**Comment by xujiaji** [comment]
好的，谢谢你的反馈！我会尽量今天抽时间解决

**Comment by xujiaji** [comment]
你用demo apk，点击“测试view改变”那个会出现这个问题吗

**Comment by xujiaji** [comment]
不知道怎么操作，不出现你这个情况。里面的切换你是咋整的呢？

**Comment by protectedMan** [comment]
刚刚我用demo的列表布局复现了一下。
问题有两个，一个是气泡在列表中被动态改变了，默认是往下扩张。
另一个是气泡被动态改变后再次show 其大小会按照dismiss前的大小来呈现。
![QQ20190411-133506-HD](https://user-images.githubusercontent.com/17565737/55933179-03635200-5c5f-11e9-9e46-ca4fd9a7f605.gif)

**Comment by protectedMan** [comment]
![QQ20190411-134130-HD](https://user-images.githubusercontent.com/17565737/55933340-99977800-5c5f-11e9-8a26-4443b2be1776.gif)
正确的效果应该是这样的

**Comment by protectedMan** [comment]
问题好像解决了，我原来在列表页oncreate的时候执行init，然后点击的时候只进行show操作。就会出现这种问题。  
我现在每次show都重新init就解决了这两个问题。

**Comment by xujiaji** [comment]
你再次show的时候有没有`setClickedView`？

**Comment by protectedMan** [comment]
> 你再次show的时候有没有`setClickedView`？[SetClickedViewTestActivity.java 83行](https://github.com/xujiaji/HappyBubble/blob/master/app/src/main/java/com/xujiaji/happybubbletest/SetClickedViewTestActivity.java)

之前show的时候是有执行setClickedView操作的。

**Comment by xujiaji** [comment]
麻烦你修改后的SetClickedViewTestActivity发一下呢，我也试试

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/55941395-b5594900-5c74-11e9-8b28-8b697f53fa89.png)
每次show之前重新创建一下BubbleDialog和ContentView就可以了
