### ISSUE TITLE
穿透事件在dialogFragment有问题

### ISSUE THREAD

**Issue by zhangzhen123** [xujiaji/HappyBubble#15]
在dialogFragment中弹出bubbleDialog  设置setThroughEvent（true,false）后，dialogfragment的视图就无法操作了 收不到触摸事件了

**Comment by xujiaji** [comment]
穿透事件其实只是传递给了activity，你这种情况事件可能需要传递给dialogfragment的dialog，需要改一下bubbledialog中的传递代码，改为传给dialogfragment

**Comment by zhangzhen123** [comment]
我是这样搞的 这样dialog就不会阻挡下层事件了
val window = bubbleDialog?.window
 window?.setFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL, WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL);

**Comment by xujiaji** [comment]
噢噢，厉害了，还有这种操作呀！
