### ISSUE TITLE
碰到的一些问题

### ISSUE THREAD

**Issue by edifangyi** [xujiaji/HappyBubble#2]
1、这种方式打开 dialog 会导致 dialog 展示在屏幕左上角，而不会显示在mIvMainToolLayer的左边。

![image](https://user-images.githubusercontent.com/12421552/34657691-e226d2c4-f463-11e7-80dc-5f2b111a2d4e.png)

![image](https://user-images.githubusercontent.com/12421552/34657649-565d5286-f463-11e7-9f8c-b1d517f9d5b9.png)

2、IllegalStateException：The specified child already has a parent. You must call removeView() on the child's parent first.
当我在外层新建View，因为需要在其他界面对view做一些操作。我的想法是 Dialog一直是存活的，只是展示和隐藏

重复new 的时候会引发上述异常崩溃。
![image](https://user-images.githubusercontent.com/12421552/34657627-05bc1e70-f463-11e7-8cb2-8e215c2912b5.png)

**Comment by edifangyi** [comment]
第一个问题，这么写倒是解决了

if (mCurrentDialog.isShowing()) {
                mCurrentDialog.setClickedView(mIvMainToolLayer).dismiss();
} else {
                mCurrentDialog.setClickedView(mIvMainToolLayer).show();
}

**Comment by edifangyi** [comment]
3、自定义View的时候，最外层容器的宽度好像不起作用
![image](https://user-images.githubusercontent.com/12421552/34658128-4ac11346-f467-11e7-9469-a1c570405630.png)

**Comment by edifangyi** [comment]
4、添加、删除布局，Dialog锚点疑问
首次打开的时候：
![qq_pic_merged_1515382520149](https://user-images.githubusercontent.com/12421552/34658229-5eae2460-f468-11e7-8e4f-50f29477ce31.jpg)

添加布局后：
![image](https://user-images.githubusercontent.com/12421552/34658227-57311ef4-f468-11e7-9053-bcdaeb8045b7.png)


使用Demo中按钮测试如下代码
固定点理应是箭头的位置，但不管是添加list还是删除list，其固定位置始终是Dialog上边的位置。

增加

![_screenshot_2018-01-08-11-51-29-066_bubbledialo](https://user-images.githubusercontent.com/12421552/34658500-84a2bff8-f46a-11e7-84e6-a183d5e8fb33.png)


删除

![screenshot_2018-01-08-11-54-46-627](https://user-images.githubusercontent.com/12421552/34658602-3b0d3318-f46b-11e7-81a9-b6de8ce4abb7.png)
![screenshot_2018-01-08-11-54-17-436](https://user-images.githubusercontent.com/12421552/34658603-3b5e115c-f46b-11e7-850f-0ab42335ae5c.png)

代码

![r4 8 k9h9th5h__16 oc](https://user-images.githubusercontent.com/12421552/34658496-7f9116ea-f46a-11e7-9c5d-7b16636739d9.png)


![image](https://user-images.githubusercontent.com/12421552/34658308-edb1ca5e-f468-11e7-9ebb-3c5aa7150c38.png)

**Comment by xujiaji** [comment]
# 第一个问题
mIvMainToolLayer没有被初始化，所以mIvMainToolLayer位置没有被确认。
你可以通过:
``` java
        mIvMainToolLayer.post(new Runnable()
        {
            @Override
            public void run()
            {
                //此时mIvMainToolLayer位置已经被初始化，将初始化Dialog代码在这里调用
            }
        });

```

# 第二个问题
你初始化的mView已经被上一个Dialog所添加，所以不能重新在新的布局中添加，你需要重新实例化一个新的mView。
# 第三个问题
目前是有这个问题，我看怎么决绝一些，现在你可以通过内层布局将外层布局撑开

**Comment by xujiaji** [comment]
关于第四个问题我没有考虑到布局变化情况下Dialog需要做出相应的改变，多谢提醒，我尽快解决

**Comment by xujiaji** [comment]
@edifangyi 我打了一个aar包，你试试能否解决你布局变化后的问题
[aar包.zip](https://github.com/xujiaji/HappyBubble/files/1610673/aar.zip)

**Comment by edifangyi** [comment]
@xujiaji 
添加数据时， 
位置在左右时，是上下高度对称展开，上下同时变宽。
位置在上时，Dialog上边不到屏幕边缘，是正常的。当上边到屏幕上的时候，箭头开始移动
位置在下时，相反。

删除的时候，位置左右，上下高度也是对称收缩，但是伴有箭头闪烁


这里是挺麻烦的，辛苦了~

**Comment by xujiaji** [comment]
@edifangyi 能不能发个视频呢？方便看下什么情况

**Comment by edifangyi** [comment]
@xujiaji   QQ  87649669
