### ISSUE TITLE
自定义气泡，设置setLookPosition无效

### ISSUE THREAD

**Issue by jun201607** [xujiaji/HappyBubble#21]
自定义气泡，设置setLookPosition无效，就算箭头的位置无效，请问是什么原因，我的qq是913811215，希望得到您的帮助。

**Comment by xujiaji** [comment]
自定义的气泡，在dialog中是无效的，因为BubbleDialog会根据你传入的view重新设置位置。
如果你要自定义气泡的setLookPosition可能你需要自己写一个Dialog或其他的布局放进去

**Comment by jun201607** [comment]
> 自定义的气泡，在dialog中是无效的，因为BubbleDialog会根据你传入的view重新设置位置。
> 如果你要自定义气泡的setLookPosition可能你需要自己写一个Dialog或其他的布局放进去

那请问怎么才能改变箭头位置，我想在弹窗里面放recyclerview

**Comment by jun201607** [comment]
> > 自定义的气泡，在dialog中是无效的，因为BubbleDialog会根据你传入的view重新设置位置。
> > 如果你要自定义气泡的setLookPosition可能你需要自己写一个Dialog或其他的布局放进去
> 
> 那请问怎么才能改变箭头位置，我想在弹窗里面放recyclerview,我现在使用的是CustomOperateDialog extends BubbleDialog这个方案，但是设置箭头位置无效

**Comment by xujiaji** [comment]
![image](https://user-images.githubusercontent.com/16447251/74210602-44852200-4cc7-11ea-9594-587d37226b2e.png)
