### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by Zvirtuey** [xujiaji/HappyBubble#24]
final View dialogMain = getLayoutInflater().inflate(R.layout.dialog_meeting_operation, null);
        tvMute = dialogMain.findViewById(R.id.stv_mute);
        tvTakenAway = dialogMain.findViewById(R.id.stv_taken_away);
        tvShutUp = dialogMain.findViewById(R.id.stv_shut_up);

bubbleDialog = new BubbleDialog(this)
                .setBubbleContentView(dialogMain)
                .setTransParentBackground()
                .setRelativeOffset(-16)
                .setThroughEvent(true, true)
                .autoPosition(Auto.UP_AND_DOWN);

mAdapter.setOnItemClickListener((holder, data) -> {
            //item 点击事件
            tvMute.setOnClickListener(this);
            tvTakenAway.setOnClickListener(this);
            tvShutUp.setOnClickListener(this);
            bubbleDialog.setClickedView(holder.itemView);
            bubbleDialog.show();
        });

1. 点击bubbleDialog外部不能消失，setThroughEvent(true, true)第二参数已经设置true了

2.setBubbleContentView的view和外部的有边距，setTransParentBackground()我理解的边框是透明的，怎么是白色的，怎么能设置边距，我想ContentView的view没有边距完全包裹。

3.在RecyclerView中item点击有的时候重复点击item，bubbleDialog会跑到上一个位置去了。

**Comment by xujiaji** [comment]
|编号|咋回事|
|:-:|:-|
|1|![image](https://user-images.githubusercontent.com/16447251/97847659-ec95bc00-1d2a-11eb-8a78-30716379a09f.png)|
|2| ![image](https://user-images.githubusercontent.com/16447251/97848026-76458980-1d2b-11eb-84d7-4302a06d6f15.png)<br/>内边距可以通过自定义`BubbleLayout`的`bubblePadding`属性修改|
|3|这个不清楚具体怎么回事了，你可以判断只点击第一次有效，或下载本框架测试一下具体情况|

**Comment by Zvirtuey** [comment]
bl.setPadding(0, 0, 0, 0);吗？ 但是没有效果， 如下图不想要蓝色的边框
![图片](https://user-images.githubusercontent.com/20436938/97938913-9f165f00-1dbd-11eb-9afc-51c7289e7fe3.png)

**Comment by xujiaji** [comment]
那个属性没有提供java实现，只有在`BubbleLayout`的xml属性`bubblePadding`设置，或下载框架添加java设置

**Comment by Zvirtuey** [comment]
看来得修改你源码了，建议后面出个版本，xml支持的属性，代码也可以支持。
