### ISSUE TITLE
如何给bubble添加图片背景

### ISSUE THREAD

**Issue by protectedMan** [xujiaji/HappyBubble#25]
![image](https://user-images.githubusercontent.com/17565737/100497129-4ce61500-3194-11eb-99d2-d00cb77cec85.png)
类似上图的效果, bubble的背景图是自定义的图片.

**Comment by xujiaji** [comment]
请更新版本到`1.2.1`
新增`BubbleLayout`xml属性`bubbleBgRes`
新增`BubbleLayout`java方法`setBubbleImageBg`和`setBubbleImageBg`

![image](https://user-images.githubusercontent.com/16447251/100498642-98052580-319e-11eb-8d16-7b9d8ee0b7f0.png)
