### ISSUE TITLE
关于 bubblePadding

### ISSUE THREAD

**Issue by protectedMan** [xujiaji/HappyBubble#27]
bubblePadding设置为0 会导致阴影区域消失,我想要的是
![image](https://user-images.githubusercontent.com/17565737/100529349-a0527480-3221-11eb-8c2e-2e7e6ded51c4.png)

bubblePadding 给值则会导致背景区域有边距,影响子布局绘制,
![image](https://user-images.githubusercontent.com/17565737/100529369-df80c580-3221-11eb-8c02-8eac826f24c3.png)

~我认为这块应该单独定义一个属性用来控制阴影的的尺寸

**Comment by xujiaji** [comment]
更新到1.2.3已修复这个问题
