### ISSUE TITLE
请支持RTL布局

### ISSUE THREAD

**Issue by zxcvbnm3057** [xujiaji/HappyBubble#32]

**Comment by xujiaji** [comment]
如果在HappyBubble上实现，可以打个比方吗？

**Comment by zxcvbnm3057** [comment]
> 如果在HappyBubble上实现，可以打个比方吗？

其实就是将箭头定位的left right替换为start end，并在内部判断LTR布局或RTL布局，将start end与left right对应

即：

- LTR布局中：start=left，end=right
- RTL布局中：start=right，end=left

感谢您提供了这样一个方便好用的控件

**Comment by xujiaji** [comment]
哦哦，懂了。可以加个这个，谢谢支持

**Comment by zxcvbnm3057** [comment]
刚升级最新版本试了下。。可能是我没说明白，RTL布局应该是LTR布局的完全镜像，但是我这里使用RTL和LTR布局的箭头lookat仍然是相同的方向
