### ISSUE TITLE
BubbleLayout嵌套exoplayer，无法播放视频

### ISSUE THREAD

**Issue by zxcvbnm3057** [xujiaji/HappyBubble#33]
布局全部使用wrap_content，将BubbleLayout替换为Framelayout显示正常，使用BubbleLayout时画面为纯白无法播放，音频正常

**Comment by zxcvbnm3057** [comment]
[TestExopLayer-master.zip](https://github.com/xujiaji/HappyBubble/files/6943203/TestExopLayer-master.zip)
这是在githubshang上随便下载的一个demo，将其原根布局修改为BubbleLayout测试，视频无法播放

原链接：https://github.com/stormdzh/TestExopLayer

**Comment by zxcvbnm3057** [comment]
望修复

**Comment by xujiaji** [comment]
噢噢，原因是在`BubbleLayout`中设置了`setLayerType(LAYER_TYPE_SOFTWARE, null);`关闭硬件加速

**Comment by xujiaji** [comment]
这个因该可以去掉，在这里加这个好像也没啥用

**Comment by zxcvbnm3057** [comment]
我将happy-bubble模块源码拉取并导入我的项目中，修改com.xujiaji.happybubble.BubbleLayout文件第112行`setLayerType(LAYER_TYPE_SOFTWARE, null);`为`setLayerType(LAYER_TYPE_HARDWARE, null);`后测试，仍无法播放；且修改后气泡失去边框。。

_我仿佛听见他在唱 “我要嚣张 嚣张到失去形状”_

**Comment by xujiaji** [comment]
注释掉就行了

**Comment by zxcvbnm3057** [comment]
注释掉可以播放，但还是无法显示气泡边框

**Comment by xujiaji** [comment]
有呢！看看你的啥样的
![image](https://user-images.githubusercontent.com/16447251/128530596-ea6c4652-d351-4c68-ac8f-84cd3b6bddcf.png)

**Comment by zxcvbnm3057** [comment]
我这边还是没用，你那边api版本是多少，我这里是Android 8.0
![%9 TC(EH8V}VAIF42S`GV@G](https://user-images.githubusercontent.com/48760372/128554779-3f70c1ef-8b8e-4b9e-9d97-7215639bb65a.png)

**Comment by xujiaji** [comment]
试了下在android8.0上把LAYER_TYPE_SOFTWARE注释掉阴影没有绘制出来

**Comment by zxcvbnm3057** [comment]
那麻烦修复一下吧。。另外希望下版本更新能加入rtl布局，谢谢

**Comment by xujiaji** [comment]
查了下在不是`LAYER_TYPE_SOFTWARE `的情况下，如果要支持阴影最低也是android9，建议你判断一下如果是android8或以下加上气泡边框的设置或改变气泡的颜色为淡灰色等
![image](https://user-images.githubusercontent.com/16447251/128590183-106f5177-a827-406e-b750-137458d5c436.png)

**Comment by xujiaji** [comment]
你有什么好的建议吗？

**Comment by zxcvbnm3057** [comment]
哦哦好的我明白了，这个气泡边框效果采用的是阴影而不是background绘制，我也想不出来什么好办法，只能判断api版本动态设置边框或者阴影了

**Comment by xujiaji** [comment]
是的，气泡的边框和阴影都是可以单独设置的，现在阴影不支持只有想到手动判断下设置边框了

**Comment by xujiaji** [comment]
![image](https://user-images.githubusercontent.com/16447251/128595480-3d46e8d1-cb8d-42af-b9a6-1dffb9c32554.png)

**Comment by zxcvbnm3057** [comment]
确实在Android 11模拟器上测试显示正常，希望这段代码也能合并到控件源码中，预计什么时候发布新版本呢

**Comment by xujiaji** [comment]
这句代码合并到新版本不合适哦！因为正常情况下8.0也是能是能显示阴影的，现在是里面放的这个视频框架的原因必须关闭`LAYER_TYPE_SOFTWARE `才导致的这个问题，你自己在findViewById后加下这个代码哦

**Comment by zxcvbnm3057** [comment]
嗯嗯好吧，个人觉得不止这个视频框架会需要硬件渲染，可能以后其他控件也会遇到类似的问题，不如把这个的解决方法放到Q&A中供后来者参考吧

**Comment by xujiaji** [comment]
可以，主要是无法知道产品的实际使用放入的控件是否需要这么设置，从接入的角度来看如果框架直接给莫名其妙设置个边框也有很奇怪，因为接入的人给气泡设置了颜色或者气泡图片本身也不需要加边框，特殊情况特殊处理了

**Comment by zxcvbnm3057** [comment]
嗯嗯好的，这个问题解决了，感谢作者的帮助，祝您生活愉快！
