### ISSUE TITLE
气泡的Y轴位置有问题

### ISSUE THREAD

**Issue by protectedMan** [xujiaji/HappyBubble#36]
![D46E0C0A-EAC3-41BA-93DE-1A16EBDB76FF](https://user-images.githubusercontent.com/17565737/139522757-755d4d6b-3bd0-4b0b-b2c9-9c95431f48b9.png)
不知道是什么原因造成的, 另一台机子位置就正常
代码:
`mCurrentDialog = new BubbleDialog(getContext())
                .setBubbleContentView(view)
                .setClickedView(ivEllipis)
                .setPosition(BubbleDialog.Position.TOP,BubbleDialog.Position.TOP);
        mCurrentDialog.show();`
另外 : 建议开放手动设置Y轴位置的API,由调用者手动设置.

**Comment by xujiaji** [comment]
试试setClickedPosition可以手动设置位置
