### ISSUE TITLE
1.2.5下载不了，1.2.4可以，是不是没上传

### ISSUE THREAD

**Issue by dulr50** [xujiaji/HappyBubble#39]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.xujiaji:happy-bubble:1.2.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://repo.maven.apache.org/maven2/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://jitpack.io/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://maven.google.com/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://repo1.maven.org/maven2/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://maven.aliyun.com/repository/central/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://maven.aliyun.com/repository/public/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://maven.aliyun.com/repository/google/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom
       - https://developer.huawei.com/repo/com/github/xujiaji/happy-bubble/1.2.5/happy-bubble-1.2.5.pom

**Comment by xujiaji** [comment]
![image](https://user-images.githubusercontent.com/16447251/146730527-33bf5459-2249-45e0-a496-eb3fe39cd47c.png)

**Comment by xujiaji** [comment]
尴尬了，确实没有发布，现在再更新试试呢，因该有了
![image](https://user-images.githubusercontent.com/16447251/146743791-635d7118-41b5-4686-8600-698dbc06b233.png)
