### ISSUE TITLE
有些疑问，请教一下

### ISSUE THREAD

**Issue by HH-Ding** [xujiaji/HappyBubble#5]
你好，我使用它在listview里，是item一个imageview长按显示。但位置一是屏幕顶部，二就是屏幕底部，请问该如何设置能让它依附与item里的imageview或者该item上。还有个问题，每次bubbleDialog显示的时候会闪烁一下，这个也请问是需要设置哪里？谢谢你抽时间回答

**Comment by xujiaji** [comment]
可以看一下你显示这部分的代码吗？

**Comment by HH-Ding** [comment]
依附问题我已解决，是setClickedView传值问题，但全屏闪烁还是在。
 if (mToastDialog == null) {//初始化
            mAuto = Auto.UP_AND_DOWN;
            mToastDialog = new CustomBubbleDialog(context)
                    .setRelativeOffset(-36)
                    .setTransParentBackground()
                    .autoPosition(mAuto);
}

显示：
 holder.rolebtn.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_UP) {
                    JYSLLogUtil.d("SDK", "松开，角色信息气泡框消失");
                    if (mToastDialog.isShowing()) {
                        mToastDialog.dismiss();
                    }
                }
                if (event.getAction() == MotionEvent.ACTION_DOWN) {
                    JYSLLogUtil.d("SDK", "登录框下拉里点击角色信息" + v.getId());
                    if (mToastDialog == null) {
                        JYSLLogUtil.d("SDK", "mToastDialog = null");
                        mAuto = Auto.UP_AND_DOWN;
                        mToastDialog = new CustomBubbleDialog(context)
                                .setTransParentBackground()
                                .autoPosition(mAuto);
                    }
                    if (!mToastDialog.isShowing()) {
                        JYSLLogUtil.d("SDK", "登录框下拉里点击角色信息 isShowing");
                        mToastDialog.setClickedView(v);
                        mToastDialog.setListIndex(v.getId());
                        mToastDialog.show();
                    }
                }
                return false;
            }
        });

**Comment by xujiaji** [comment]
你在show（）那里打一下log看看有没有重复了显示呢？如果没有那我的回去看一看代码

**Comment by HH-Ding** [comment]
没有重复，长按的时候，isShow()下的只执行了一次


04-09 11:52:02.428 29693-29693/com.tencent.tmgp.shjx9130 D/SDK: 登录框下拉里点击角色信息2
04-09 11:52:02.428 29693-29693/com.tencent.tmgp.shjx9130 D/SDK: 登录框下拉里点击角色信息 isShowing
04-09 11:52:02.438 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:02.450 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:02.463 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:02.543 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:02.565 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:02.586 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:02.816 1426-1503/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{a3e83b7 u0 com.tencent.tmgp.shjx9130/com.jysl.gamedemo.JyslSdk_Game_Activity} token=android.os.Binder@f8e7aca which=1
04-09 11:52:04.555 29693-29693/com.tencent.tmgp.shjx9130 D/SDK: 松开，角色信息气泡框消失

**Comment by xujiaji** [comment]
好的，不过要下午或者晚上来看看了

**Comment by xujiaji** [comment]
还有怎么个闪法？可以截几张图看看吗

**Comment by xujiaji** [comment]
方便的话加一下我的QQ吧！
624719201
