### ISSUE TITLE
显示 bubble 时的背景色能否自定义？

### ISSUE THREAD

**Issue by DanteAndroid** [xujiaji/HappyBubble#7]
就是想做一个引导的效果。以及显示 bubble 如何加上自定义动画？谢谢

**Comment by xujiaji** [comment]
设置动画和Dialog的设置方法一样，可以看我刚刚更新的代码。
可以设置透明度，但是如果你想设置背景颜色，还真是不好办！
如果实在想要背景色，我的思路是：在你的布局顶部添加颜色背景（隐藏），bubble设置成透明，弹出时显示你隐藏的颜色背景。

**Comment by DanteAndroid** [comment]
感谢
