### ISSUE TITLE
自动方向问题

### ISSUE THREAD

**Issue by Silnt** [xujiaji/HappyBubble#9]
是否可以设置方向优先级
比如 设置下方显示 当下方的空间不足时 自动调整为上方显示 左右也是如此
实例代码中 没有看到 gif 中设置 BubbleLayout 外边距的代码啊

**Comment by xujiaji** [comment]
你好，请问自动方向有什么问题？以方便检查，如果能提供Gif或png截图就更好了

**Comment by xujiaji** [comment]
方向优先级这个不错，可以加！

BubbleLayout的设置方法在BubbleLayout中，可以通过调用BubbleDialog的`setBubbleLayout`方法，自定义BubbleLayout

**Comment by Silnt** [comment]
![1536569832607](https://user-images.githubusercontent.com/21040178/45287337-95b14500-b51a-11e8-9ee6-03b343e7d23e.jpg)
这个 我看 1.0的代码好像有 现在的没有了 是去掉了吗

**Comment by Silnt** [comment]
看到了 设置padding  不过 我想要的事外边距的效果 呵呵
使用的时候 发现 bubblePadding 属性好像没有提供 代码中设置的方法啊
只能在xml中使用

**Comment by xujiaji** [comment]
bubblePadding就相当于外边距效果，如果你想设置真的外边距，可以通过getLayoutParams来设置margin

**Comment by Silnt** [comment]
好的

**Comment by xujiaji** [comment]
请问你对于优先级的设置方式有什么建议吗

**Comment by Silnt** [comment]
4中模式 先上后下  先下后上 先左后右 先右后左

**Comment by xujiaji** [comment]
感觉这样会多了好多方法呀！这样吧，通过可变参数，传入上下左右，排最前面的优先级越高

**Comment by Silnt** [comment]
setPosition

**Comment by Silnt** [comment]
那你直接 把 setPosition 方法的参数 改为可变参数 autoPosition 就不用了  而且也不用 新增方法
之前的用户 都不不用改代码 就可以使用了

**Comment by xujiaji** [comment]
好主意
